Entry.create name: 'Star Wars Episode I: The Phantom Menace'
Entry.create name: 'Star Wars Episode II: Attack of the Clones'
Entry.create name: 'Star Wars Episode III: Revenge of the Sith'
Entry.create name: 'Star Wars Episode IV: A New Hope'
Entry.create name: 'Star Wars Episode V: The Empire Strikes Back'
Entry.create name: 'Star Wars Episode VI: Return of the Jedi'
